apiVersion: v1
kind: Secret
metadata:
  name: lms-secrets
  namespace: lms
type: Opaque
stringData:
  SECRET_KEY: "your_random_secret_key_here"
  GROQ_API_KEY: "replace_with_groq_api_key"
  GOOGLE_CLIENT_ID: "882821702139-gt4nkra8d8sp9s836jpbg87j96mt1o07.apps.googleusercontent.com"
  POSTGRES_PASSWORD: "password"
